# Generated by Django 4.1.6 on 2023-10-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_branch_certificate_course_group_planlessons_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finished_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
