# Generated by Django 4.1.6 on 2023-10-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_group_finished_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
    ]
