# Generated by Django 4.1.6 on 2023-10-30 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_debt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
