# Generated by Django 4.1.6 on 2023-10-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_banner_faq_feature_galleryphoto_ieltsresult_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_numbers',
        ),
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='photos',
        ),
        migrations.DeleteModel(
            name='IeltsResult',
        ),
        migrations.DeleteModel(
            name='JobMessage',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='desired_course',
            new_name='desiredCourse',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='image',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='GalleryPhoto',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
