# Generated by Django 4.1.6 on 2023-10-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_banner_remove_contact_phone_numbers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='finished_at',
            field=models.DateField(blank=True),
        ),
    ]
