# Generated by Django 4.1.6 on 2023-11-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_group_finished_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
